# ReturnIQ: Exploratory Data Analysis (EDA)

## 3. Exploratory Analysis

This notebook analyses the cleaned and engineered ReturnIQ dataset.

The analysis focuses on:

- Dataset structure
- Order status
- Delivery performance and delay
- Customer review scores
- Product categories
- Seller performance
- Price and freight
- Seller-customer distance
- Transit speed
- Single-item vs multi-item orders
- Correlations and feature relationships
- External complaint evidence from NCH
- Return/cancellation signals from Online Retail II

EDA findings describe observed patterns and associations. They should not be interpreted as causal relationships.

## 3.1 Load the Cleaned Analytical Dataset

In [1]:
%run 01_Data_Loading.ipynb
%run 02_Data_Cleaning.ipynb
import pandas as pd
import numpy as np

# Load the integrated dataset created by 02_Data_Cleaning.ipynb.
df = pd.read_csv("data/cleaned/returniq_integrated_features.csv")

# Restore datetime columns used in EDA calculations.
datetime_columns = [
    "shipping_limit_date",
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in datetime_columns:
    if column in df.columns:
        df[column] = pd.to_datetime(df[column], errors="coerce")

order_items_complete = df

# Load cleaned external datasets used in the final EDA.
df_complaints_clean = pd.read_csv("data/cleaned/complaints_cleaned.csv")
df_online_retail_clean = pd.read_csv("data/cleaned/online_retail_cleaned.csv")

print("Integrated dataset:", order_items_complete.shape)
print("Complaint dataset:", df_complaints_clean.shape)
print("Online Retail II:", df_online_retail_clean.shape)

Customers: 99441 rows, 5 columns
Geolocation: 1000163 rows, 5 columns
Order Items: 112650 rows, 7 columns
Payments: 103886 rows, 5 columns
Reviews: 99224 rows, 7 columns
Orders: 99441 rows, 8 columns
Products: 32951 rows, 9 columns
Sellers: 3095 rows, 4 columns
Translation: 71 rows, 2 columns
Online Retail II: 525461 rows, 8 columns
============================================================
Customers
Rows: 99441
Columns: 5
Column names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
Geolocation
Rows: 1000163
Columns: 5
Column names:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
Order Items
Rows: 112650
Columns: 7
Column names:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
Payments
Rows: 103886
Columns: 5
Column names:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
Reviews
Rows: 99224
Columns: 7
Column names:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
Orders
Rows: 99441
Columns: 8
Column names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
Products
Rows: 32951
Columns: 9
Column names:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
Sellers
Rows: 3095
Columns: 4
Column names:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
Translation
Rows: 71
Columns: 2
Column names:
['product_category_name', 'product_category_name_english']

============================================================
Online Retail II
Rows: 525461
Columns: 8
Column names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

============================================================
Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

============================================================
Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

============================================================
Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

============================================================
Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

============================================================
Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

============================================================
Orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

============================================================
Products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

============================================================
Sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

============================================================
Translation
product_category_name            0
product_category_name_english    0
dtype: int64

============================================================
Online Retail II
Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

============================================================
Customers
Duplicate rows: 0

============================================================
Geolocation
Duplicate rows: 261831

============================================================
Order Items
Duplicate rows: 0

============================================================
Payments
Duplicate rows: 0

============================================================
Reviews
Duplicate rows: 0

============================================================
Orders
Duplicate rows: 0

============================================================
Products
Duplicate rows: 0

============================================================
Sellers
Duplicate rows: 0

============================================================
Translation
Duplicate rows: 0

============================================================
Online Retail II
Duplicate rows: 6865

(12, 3)
['Sl. No.', 'Nature of Grievances', 'Number of Grievances Received on NCH']
  Sl. No.                    Nature of Grievances  \
0       1                  Deficiency in Services
1       2               Delivery of Wrong Product
2       3  Delivery of Defective / Damage Product
3       4                Paid amount not refunded
4       5                 Non-Delivery of Product

   Number of Grievances Received on NCH
0                                 59723
1                                 54563
2                                 53285
3                                 50997
4                                 42781
Customers: 99441 rows, 5 columns
Geolocation: 1000163 rows, 5 columns
Order Items: 112650 rows, 7 columns
Payments: 103886 rows, 5 columns
Reviews: 99224 rows, 7 columns
Orders: 99441 rows, 8 columns
Products: 32951 rows, 9 columns
Sellers: 3095 rows, 4 columns
Translation: 71 rows, 2 columns
Online Retail II: 525461 rows, 8 columns
============================================================
Customers
Rows: 99441
Columns: 5
Column names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
Geolocation
Rows: 1000163
Columns: 5
Column names:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
Order Items
Rows: 112650
Columns: 7
Column names:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
Payments
Rows: 103886
Columns: 5
Column names:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
Reviews
Rows: 99224
Columns: 7
Column names:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
Orders
Rows: 99441
Columns: 8
Column names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
Products
Rows: 32951
Columns: 9
Column names:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
Sellers
Rows: 3095
Columns: 4
Column names:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
Translation
Rows: 71
Columns: 2
Column names:
['product_category_name', 'product_category_name_english']

============================================================
Online Retail II
Rows: 525461
Columns: 8
Column names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

============================================================
Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

============================================================
Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

============================================================
Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

============================================================
Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

============================================================
Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

============================================================
Orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

============================================================
Products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

============================================================
Sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

============================================================
Translation
product_category_name            0
product_category_name_english    0
dtype: int64

============================================================
Online Retail II
Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

============================================================
Customers
Duplicate rows: 0

============================================================
Geolocation
Duplicate rows: 261831

============================================================
Order Items
Duplicate rows: 0

============================================================
Payments
Duplicate rows: 0

============================================================
Reviews
Duplicate rows: 0

============================================================
Orders
Duplicate rows: 0

============================================================
Products
Duplicate rows: 0

============================================================
Sellers
Duplicate rows: 0

============================================================
Translation
Duplicate rows: 0

============================================================
Online Retail II
Duplicate rows: 6865

(12, 3)
['Sl. No.', 'Nature of Grievances', 'Number of Grievances Received on NCH']
  Sl. No.                    Nature of Grievances  \
0       1                  Deficiency in Services
1       2               Delivery of Wrong Product
2       3  Delivery of Defective / Damage Product
3       4                Paid amount not refunded
4       5                 Non-Delivery of Product

   Number of Grievances Received on NCH
0                                 59723
1                                 54563
2                                 53285
3                                 50997
4                                 42781
Original rows: 1000163
Duplicate rows: 261831
Unique ZIP codes: 19015
Total rows: 1000163
Original rows: 1000163
Cleaned rows: 738332
Rows removed: 261831
Duplicates remaining: 0
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64
Invalid review scores:
Empty DataFrame
Columns: [review_id, order_id, review_score]
Index: []
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
Reviews cleaned successfully!
Rows: 99224
Columns: 7
Duplicates: 0
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64
              order_purchase_timestamp  order_approved_at  \
order_status
approved                             0                  0
canceled                             0                141
created                              0                  5
delivered                            0                 14
invoiced                             0                  0
processing                           0                  0
shipped                              0                  0
unavailable                          0                  0

              order_delivered_carrier_date  order_delivered_customer_date  \
order_status
approved                                 2                              2
canceled                               550                            619
created                                  5                              5
delivered                                2                              8
invoiced                               314                            314
processing                             301                            301
shipped                                  0                           1107
unavailable                            609                            609

              order_estimated_delivery_date
order_status
approved                                  0
canceled                                  0
created                                   0
delivered                                 0
invoiced                                  0
processing                                0
shipped                                   0
unavailable                               0
Orders cleaned successfully!
Rows: 99441
Columns: 8
Duplicates: 0
Invalid delivery dates: 0
Invalid carrier dates: 166
order_status
delivered    165
shipped        1
Name: count, dtype: int64
count                         166
mean     -2 days +21:57:37.879519
std       13 days 06:55:25.842359
min           -172 days +18:54:07
25%             -1 days +22:58:57
50%      -1 days +23:24:00.500000
75%             -1 days +23:45:56
max             -1 days +23:59:36
Name: carrier_difference, dtype: object
Invalid carrier dates fixed: 166
Remaining invalid carrier dates: 0
Orders shape: (99441, 8)

Missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1949
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate rows: 0
Products shape: (32951, 9)

Missing values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate rows: 0
Rows with missing category: 610

Missing values in these rows:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64
                             product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes
18851  5eb564652db742ff8f28759cd8d2652a                   NaN

       product_name_lenght  product_description_lenght  product_photos_qty  \
8578                  60.0                       865.0                 3.0
18851                  NaN                         NaN                 NaN

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN
18851               NaN                NaN                NaN

       product_width_cm
8578                NaN
18851               NaN
Missing-category products: 610
Translation rows: 71
Products with missing physical information:
                             product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes
18851  5eb564652db742ff8f28759cd8d2652a                   NaN

       product_name_lenght  product_description_lenght  product_photos_qty  \
8578                  60.0                       865.0                 3.0
18851                  NaN                         NaN                 NaN

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN
18851               NaN                NaN                NaN

       product_width_cm
8578                NaN
18851               NaN
Total products: 32951
Unique product IDs: 32951
Duplicate product IDs: 0
Sellers shape: (3095, 4)

Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate rows: 0

Duplicate seller IDs: 0
Translation shape: (71, 2)

Missing values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate rows: 0

Duplicate Portuguese categories: 0

Duplicate English categories: 0
Online Retail II shape: (525461, 8)

Missing values:
Invoice             0

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

Quantity statistics:
count    525461.000000
mean         10.337667
std         107.424110
min       -9600.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       19152.000000
Name: Quantity, dtype: float64

Price statistics:
count    525461.000000
mean          4.688834
std         146.126914
min      -53594.360000
25%           1.250000
50%           2.100000
75%           4.210000
max       25111.090000
Name: Price, dtype: float64
Negative Quantity rows: 12326
Negative Price rows: 3

Rows with negative Quantity:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
197,C489459,90200D,PINK SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
198,C489459,90200B,BLACK SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
199,C489459,90200E,GREEN SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
200,C489459,90200C,BLUE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
201,C489459,90185C,BLACK DIAMANTE EXPANDABLE RING,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
202,C489459,90185B,AMETHYST DIAMANTE EXPANDABLE RING,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
203,C489459,90003C,MIDNIGHT BLUE PAIR HEART HAIR SLIDE,-3,2009-12-01 10:44:00,3.75,17592.0,United Kingdom
204,C489459,90003D,CRYSTAL PAIR HEART HAIR SLIDES,-3,2009-12-01 10:44:00,3.75,17592.0,United Kingdom
205,C489459,90003B,ROSE COLOUR PAIR HEART HAIR SLIDES,-3,2009-12-01 10:44:00,3.75,17592.0,United Kingdom
206,C489459,90209C,PINK ENAMEL+GLASS HAIR COMB,-3,2009-12-01 10:44:00,2.10,17592.0,United Kingdom

Rows with negative Price:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

Invoice values for negative quantities:
['C489449', 'C489449', 'C489449', 'C489449', 'C489449', 'C489449', 'C489449', 'C489449', 'C489449', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 'C489459', 489464, 489463, 489467, 'C489476', 'C489503', 'C489503', 'C489504', 'C489518']

Invoice prefix counts:
Invoice
C    10205
5     1392
4      729
Name: count, dtype: int64
Zero-price transactions: 3687
Negative-price transactions: 3

Negative-price examples:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

Zero-price rows: 3687

Sample zero-price transactions:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom
5904,489861,DOT,DOTCOM POSTAGE,1,2009-12-02 14:50:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom

Zero-price descriptions:
Description
?                                      45
damages                                39
damaged                                38
missing                                24
OWL DOORSTOP                            8
checked                                 8
POLYESTER FILLER PAD 45x45cm            7
PICNIC BASKET WICKER LARGE              7
FLAG OF ST GEORGE CAR FLAG              6
dotcom                                  6
HEART OF WICKER SMALL                   6
AIRLINE BAG VINTAGE WORLD CHAMPION      6
given away                              6
smashed                                 5
POLYESTER FILLER PAD 40x40cm            5
SMALL POPCORN HOLDER                    5
WATERING CAN BLUE ELEPHANT              5
ENAMEL FIRE BUCKET CREAM                5
ENAMEL WASH BOWL CREAM                  5
PICNIC BASKET WICKER SMALL              5
Name: count, dtype: int64

Zero-price invoice prefixes:
Invoice
5    2579
4    1108
Name: count, dtype: int64
Rows with missing Customer ID: 107927

Countries:
Country
United Kingdom          106429
EIRE                       960
United Arab Emirates       114
Portugal                    77
Hong Kong                   76
Bahrain                     65
France                      62
RSA                         46
Bermuda                     34
Unspecified                 30
Sweden                      19
Lebanon                     13
Nigeria                      2
Name: count, dtype: int64

Quantity statistics:
count    107927.000000
mean          0.971045
std         128.207415
min       -9600.000000
25%           1.000000
50%           1.000000
75%           2.000000
max       10200.000000
Name: Quantity, dtype: float64

Sample:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1058,489548,22195,LARGE HEART MEASURING SPOONS,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom
1059,489548,22131,FOOD CONTAINER SET 3 LOVE HEART,2,2009-12-01 12:32:00,1.95,NaN,United Kingdom
1060,489548,22079,RIBBON REEL HEARTS DESIGN,10,2009-12-01 12:32:00,1.65,NaN,United Kingdom
1061,489548,22138,BAKING SET 9 PIECE RETROSPOT,3,2009-12-01 12:32:00,4.95,NaN,United Kingdom
1062,489548,22147,FELTCRAFT BUTTERFLY HEARTS,2,2009-12-01 12:32:00,1.45,NaN,United Kingdom
1063,489548,22142,CHRISTMAS CRAFT WHITE FAIRY,2,2009-12-01 12:32:00,1.45,NaN,United Kingdom
1064,489548,22150,3 STRIPEY MICE FELTCRAFT,2,2009-12-01 12:32:00,1.95,NaN,United Kingdom
1065,489548,20804,GLASS CHICKEN BUTTER DISH,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom
1066,489548,22196,SMALL HEART MEASURING SPOONS,8,2009-12-01 12:32:00,0.85,NaN,United Kingdom
1067,489548,22086,PAPER CHAIN KIT 50'S CHRISTMAS,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1068,489548,21115,ROSE CARAVAN DOORSTOP,1,2009-12-01 12:32:00,6.75,NaN,United Kingdom

Missing Description rows: 2928

Quantity statistics:
count    2928.000000
mean      -21.186475
std       599.532127
min     -9600.000000
25%       -30.000000
50%        -4.500000
75%         3.000000
max      9600.000000
Name: Quantity, dtype: float64

Price statistics:
count    2928.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: Price, dtype: float64

Sample:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
7204,490015,21982,NaN,467,2009-12-03 12:29:00,0.0,NaN,United Kingdom
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9249,490123,84508B,NaN,184,2009-12-03 18:08:00,0.0,NaN,United Kingdom
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10236,490150,84347,NaN,80,2009-12-04 09:44:00,0.0,NaN,United Kingdom
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom
11973,490354,21489,NaN,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom
12237,490379,21490,NaN,-44,2009-12-05 13:26:00,0.0,NaN,United Kingdom

Invoice prefix:
Invoice
5    1880
4    1048
Name: count, dtype: int64

Missing Customer ID:
2928
Rows involved in duplicate groups: 13283

Sample duplicate rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
721,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
723,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
716,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
725,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
772,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
856,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
826,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom
840,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom
830,489536,21579,LOLITA DESIGN COTTON TOTE BAG,1,2009-12-01 12:13:00,2.25,16393.0,United Kingdom

Duplicate rows with negative quantity: 47
Duplicate rows with zero price: 12
Duplicate rows with positive quantity: 13236
Rows before removing duplicates: 525461
Rows after removing duplicates: 518596
Duplicate rows removed: 6865
Remaining duplicate rows: 0
Zero-price rows: 3681

Zero-price rows with positive quantity: 1560
Zero-price rows with negative quantity: 2121

Top descriptions:

Description
?                                      45
damages                                39
damaged                                38
missing                                24
OWL DOORSTOP                            8
checked                                 8
POLYESTER FILLER PAD 45x45cm            7
PICNIC BASKET WICKER LARGE              7
FLAG OF ST GEORGE CAR FLAG              6
dotcom                                  6
given away                              6
smashed                                 5
POLYESTER FILLER PAD 40x40cm            5
SMALL POPCORN HOLDER                    5
WATERING CAN BLUE ELEPHANT              5
HEART OF WICKER SMALL                   5
ENAMEL FIRE BUCKET CREAM                5
ENAMEL WASH BOWL CREAM                  5
AIRLINE BAG VINTAGE WORLD CHAMPION      5
PICNIC BASKET WICKER SMALL              5
Name: count, dtype: int64

Rows before removing zero-price records: 518596
Rows after removing zero-price records: 514915
Zero-price rows removed: 3681

Remaining zero-price rows: 0
Negative-price rows: 3

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

Rows before removing negative-price records: 514915
Rows after removing negative-price records: 514912
Negative-price rows removed: 3

Remaining negative-price rows: 0
===== FINAL ONLINE RETAIL II CHECK =====
Shape: (514912, 8)

Missing values:
Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    104180
Country             0
dtype: int64

Duplicate rows: 0

Negative quantity: 10181
Zero quantity: 0
Positive quantity: 504731

Negative price: 0
Zero price: 0
Positive price: 514912

Data types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object
Shape: (12, 3)

Columns:
['Sl. No.', 'Nature of Grievances', 'Number of Grievances Received on NCH']

Missing values:
Sl. No.                                 0
Nature of Grievances                    0
Number of Grievances Received on NCH    0
dtype: int64

Duplicate rows:
0

,Sl. No.,Nature of Grievances,Number of Grievances Received on NCH
0,1,Deficiency in Services,59723
1,2,Delivery of Wrong Product,54563
2,3,Delivery of Defective / Damage Product,53285
3,4,Paid amount not refunded,50997
4,5,Non-Delivery of Product,42781
5,6,Delay in Delivery of Product,27394
6,7,Replacement / Refund not provided - As per policy,19020
7,8,Amount Debited but Not Credited to Beneficiary,15315
8,9,Product / Product Accessories Missing,15077
9,10,Account Blocked/Service Barred,5913
10,11,Others,53265
11,Grand Total,Grand Total,397333

Original rows: 12
Cleaned rows: 11

Remaining categories:

,Sl. No.,Nature of Grievances,Number of Grievances Received on NCH
0,1,Deficiency in Services,59723
1,2,Delivery of Wrong Product,54563
2,3,Delivery of Defective / Damage Product,53285
3,4,Paid amount not refunded,50997
4,5,Non-Delivery of Product,42781
5,6,Delay in Delivery of Product,27394
6,7,Replacement / Refund not provided - As per policy,19020
7,8,Amount Debited but Not Credited to Beneficiary,15315
8,9,Product / Product Accessories Missing,15077
9,10,Account Blocked/Service Barred,5913
10,11,Others,53265

CUSTOMER IDs
Orders customer_id: 99441
Customers customer_id: 99441

ORDER IDs
Orders: 99441
Order Items: 98666
Payments: 99440
Reviews: 98673

PRODUCT IDs
Products: 32951
Order Items: 32951

SELLER IDs
Sellers: 3095
Order Items: 3095
===== ID MATCHING CHECK =====
Orders with customer_id not found in Customers: 0
Order Items with order_id not found in Orders: 0
Payments with order_id not found in Orders: 0
Reviews with order_id not found in Orders: 0
Order Items with product_id not found in Products: 0
Order Items with seller_id not found in Sellers: 0
===== PAYMENT RECORDS PER ORDER =====
1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

Maximum payments for one order: 29

===== REVIEW RECORDS PER ORDER =====
1    98126
2      543
3        4
Name: count, dtype: int64

Maximum reviews for one order: 3
===== PAYMENT TYPES =====
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

===== PAYMENT TYPE + ORDER COUNT =====
payment_type
credit_card    76505
boleto         19784
voucher         3866
debit_card      1528
not_defined        3
Name: order_id, dtype: int64

===== PAYMENT VALUE CHECK =====
count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64
Payment aggregated shape: (99440, 5)

,order_id,payment_total_value,payment_count,payment_max_installments,payment_types
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,2,credit_card
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,3,credit_card
2,000229ec398224ef6ca0657da4fc703e,216.87,1,5,credit_card
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,2,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,3,credit_card

Review aggregated shape: (98673, 5)

,order_id,review_score_mean,review_score_min,review_score_count,review_comments
0,00010242fe8c5a6d1ba2dd792cb16214,5.0,5,1,"Perfeito, produto entregue antes do combinado."
1,00018f77f2f0320c557190d7a144bdd3,4.0,4,1,
2,000229ec398224ef6ca0657da4fc703e,5.0,5,1,Chegou antes do prazo previsto e o produto sur...
3,00024acbcdf0a6daa1e931b038114c75,4.0,4,1,
4,00042b26cf59d7ce69dfabb4e55b4fd9,5.0,5,1,Gostei pois veio no prazo determinado .

Payment aggregated shape: (99440, 5)

,order_id,payment_total_value,payment_count,payment_max_installments,payment_types
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,2,credit_card
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,3,credit_card
2,000229ec398224ef6ca0657da4fc703e,216.87,1,5,credit_card
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,2,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,3,credit_card

Products for merge: (32951, 6)
Sellers for merge: (3095, 4)
Order Items shape: (112650, 7)
After Products merge: (112650, 12)
After Sellers merge: (112650, 15)
Orders for merge: (99441, 8)
Before Orders merge: (112650, 15)
After Orders merge: (112650, 22)
Customers for merge: (99441, 5)
Before Customers merge: (112650, 22)
After Customers merge: (112650, 26)
Before Payments merge: (112650, 26)
After Payments merge: (112650, 30)
Before Reviews merge: (112650, 30)
After Reviews merge: (112650, 34)
Shape: (112650, 34)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'product_category_name', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'seller_zip_code_prefix', 'seller_city', 'seller_state', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'payment_total_value', 'payment_count', 'payment_max_installments', 'payment_types', 'review_score_mean', 'review_score_min', 'review_score_count', 'review_comments']

Duplicate rows: 0

Missing values:
order_id                            0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
product_category_name            1603
product_weight_g                   18
product_length_cm                  18
product_height_cm                  18
product_width_cm                   18
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1381
order_delivered_customer_date    2454
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_total_value                 3
payment_count                       3
payment_max_installments            3
payment_types                       3
review_score_mean                 942
review_score_min                  942
review_score_count                942
review_comments                   942
dtype: int64
Orders without payment information: 3
Orders without review information: 942

Order status distribution:
order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

Product category missing: 1603
Shape after translation: (112650, 35)

Missing English categories: 1627

Sample:
   product_category_name product_category_name_english
0             cool_stuff                    cool_stuff
1               pet_shop                      pet_shop
2       moveis_decoracao               furniture_decor
3             perfumaria                     perfumery
4     ferramentas_jardim                  garden_tools
5  utilidades_domesticas                    housewares
6              telefonia                     telephony
7     ferramentas_jardim                  garden_tools
8           beleza_saude                 health_beauty
9        livros_tecnicos               books_technical
product_category_name
portateis_cozinha_e_preparadores_de_alimentos    15
pc_gamer                                          9
Name: count, dtype: int64
Untranslated unique categories: 2
Order items affected: 24
Missing English categories after mapping: 1603

Mapped categories:
                               product_category_name  \
3228   portateis_cozinha_e_preparadores_de_alimentos
12976                                       pc_gamer

         product_category_name_english
3228   portable_kitchen_food_preparers
12976                        gaming_pc
Geolocation aggregated shape: (19015, 3)

Unique ZIP prefixes: 19015

Duplicate ZIP prefixes: 0

Sample:
   geolocation_zip_code_prefix   latitude  longitude
0                         1001 -23.550227 -46.634039
1                         1002 -23.547657 -46.634991
2                         1003 -23.549000 -46.635582
3                         1004 -23.549829 -46.634792
4                         1005 -23.549547 -46.636406
Shape after customer geolocation: (112650, 37)

Missing customer latitude: 302
Missing customer longitude: 302
Shape after seller geolocation: (112650, 39)

Missing seller latitude: 253
Missing seller longitude: 253
Final shape: (112650, 39)

Duplicate rows: 0

Total missing values: 12018

Columns: 39
order_delivered_customer_date    2454
product_category_name            1603
product_category_name_english    1603
order_delivered_carrier_date     1381
review_score_mean                 942
review_score_min                  942
review_score_count                942
review_comments                   942
customer_latitude                 302
customer_longitude                302
seller_latitude                   253
seller_longitude                  253
product_width_cm                   18
product_length_cm                  18
product_height_cm                  18
product_weight_g                   18
order_approved_at                  15
payment_total_value                 3
payment_max_installments            3
payment_types                       3
payment_count                       3
dtype: int64
Total missing values: 12018
Columns with missing values: 21
Review available:
review_available
1    111708
0       942
Name: count, dtype: int64

Payment available:
payment_available
1    112647
0         3
Name: count, dtype: int64
Missing Portuguese category: 0
Missing English category: 0
product_weight_g → median used: 700.0
product_length_cm → median used: 25.0
product_height_cm → median used: 13.0
product_width_cm → median used: 20.0

Missing product measurements after filling:
product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64
Missing payment values:
payment_total_value         0
payment_count               0
payment_max_installments    0
payment_types               0
dtype: int64
Missing review comments: 0
Missing review scores: 942
Missing review count: 942
Carrier delivery available:
carrier_delivery_available
1    111269
0      1381
Name: count, dtype: int64

Customer delivery available:
customer_delivery_available
1    110196
0      2454
Name: count, dtype: int64
Approval available:
approval_available
1    112635
0        15
Name: count, dtype: int64

Missing approval dates: 15
Customer location available:
customer_location_available
1    112348
0       302
Name: count, dtype: int64

Seller location available:
seller_location_available
1    112397
0       253
Name: count, dtype: int64

Missing customer latitude: 302
Missing seller latitude: 253
Total missing values: 7786

Remaining missing values:
order_delivered_customer_date    2454
order_delivered_carrier_date     1381
review_score_mean                 942
review_score_min                  942
review_score_count                942
customer_latitude                 302
customer_longitude                302
seller_latitude                   253
seller_longitude                  253
order_approved_at                  15
dtype: int64
Final shape: (112650, 46)
Duplicate rows: 0
   delivery_days  estimated_delivery_days  delivery_delay_days  is_delayed
0            7.0                       15                 -9.0           0
1           16.0                       18                 -3.0           0
2            7.0                       21                -14.0           0
3            6.0                       11                 -6.0           0
4           25.0                       40                -16.0           0
5            6.0                       21                -15.0           0
6            8.0                       24                -17.0           0
7            5.0                       20                -16.0           0
8            9.0                        9                  0.0           0
9            2.0                       20                -19.0           0
is_delayed
0       102931
1         7265
<NA>      2454
Name: count, dtype: int64
    price  freight_value  item_total_value  payment_total_value  \
0   58.90          13.29             72.19                72.19
1  239.90          19.93            259.83               259.83
2  199.00          17.87            216.87               216.87
3   12.99          12.79             25.78                25.78
4  199.90          18.14            218.04               218.04
5   21.90          12.69             34.59                34.59
6   19.90          11.85             31.75                31.75
7  810.00          70.75            880.75               880.75
8  145.95          11.65            157.60               157.60
9   53.99          11.40             65.39                65.39

   payment_difference
0        0.000000e+00
1        0.000000e+00
2        0.000000e+00
3        0.000000e+00
4       -2.842171e-14
5        7.105427e-15
6        0.000000e+00
7        0.000000e+00
8        0.000000e+00
9        0.000000e+00
   item_total_value  payment_total_value  payment_difference
0             72.19                72.19                 0.0
1            259.83               259.83                 0.0
2            216.87               216.87                 0.0
3             25.78                25.78                 0.0
4            218.04               218.04                -0.0
5             34.59                34.59                 0.0
6             31.75                31.75                 0.0
7            880.75               880.75                 0.0
8            157.60               157.60                 0.0
9             65.39                65.39                 0.0
                            order_id  order_item_id  order_item_count
0   00010242fe8c5a6d1ba2dd792cb16214              1                 1
1   00018f77f2f0320c557190d7a144bdd3              1                 1
2   000229ec398224ef6ca0657da4fc703e              1                 1
3   00024acbcdf0a6daa1e931b038114c75              1                 1
4   00042b26cf59d7ce69dfabb4e55b4fd9              1                 1
5   00048cc3ae777c65dbb7d2a0634bc1ea              1                 1
6   00054e8431b9d7675808bcb819fb4a32              1                 1
7   000576fe39319847cbb9d288c5617fa6              1                 1
8   0005a1a1728c9d785b8e2b08b904576c              1                 1
9   0005f50442cb953dcd1d21e1fb923495              1                 1
10  00061f2a7bc09da83e415a52dc8a4af1              1                 1
11  00063b381e2406b52ad429470734ebd5              1                 1
12  0006ec9db01a64e59a68b2c340bf65a7              1                 1
13  0008288aa423d2a3f00fcb17cd7d8719              1                 2
14  0008288aa423d2a3f00fcb17cd7d8719              2                 2
                            order_id  item_total_value  order_item_count  \
0   00010242fe8c5a6d1ba2dd792cb16214             72.19                 1
1   00018f77f2f0320c557190d7a144bdd3            259.83                 1
2   000229ec398224ef6ca0657da4fc703e            216.87                 1
3   00024acbcdf0a6daa1e931b038114c75             25.78                 1
4   00042b26cf59d7ce69dfabb4e55b4fd9            218.04                 1
5   00048cc3ae777c65dbb7d2a0634bc1ea             34.59                 1
6   00054e8431b9d7675808bcb819fb4a32             31.75                 1
7   000576fe39319847cbb9d288c5617fa6            880.75                 1
8   0005a1a1728c9d785b8e2b08b904576c            157.60                 1
9   0005f50442cb953dcd1d21e1fb923495             65.39                 1
10  00061f2a7bc09da83e415a52dc8a4af1             68.87                 1
11  00063b381e2406b52ad429470734ebd5             57.98                 1
12  0006ec9db01a64e59a68b2c340bf65a7             97.32                 1
13  0008288aa423d2a3f00fcb17cd7d8719             63.27                 2
14  0008288aa423d2a3f00fcb17cd7d8719             63.27                 2

    order_total_value
0               72.19
1              259.83
2              216.87
3               25.78
4              218.04
5               34.59
6               31.75
7              880.75
8              157.60
9               65.39
10              68.87
11              57.98
12              97.32
13             126.54
14             126.54
                            order_id  order_item_count  is_multi_item_order
0   00010242fe8c5a6d1ba2dd792cb16214                 1                    0
1   00018f77f2f0320c557190d7a144bdd3                 1                    0
2   000229ec398224ef6ca0657da4fc703e                 1                    0
3   00024acbcdf0a6daa1e931b038114c75                 1                    0
4   00042b26cf59d7ce69dfabb4e55b4fd9                 1                    0
5   00048cc3ae777c65dbb7d2a0634bc1ea                 1                    0
6   00054e8431b9d7675808bcb819fb4a32                 1                    0
7   000576fe39319847cbb9d288c5617fa6                 1                    0
8   0005a1a1728c9d785b8e2b08b904576c                 1                    0
9   0005f50442cb953dcd1d21e1fb923495                 1                    0
10  00061f2a7bc09da83e415a52dc8a4af1                 1                    0
11  00063b381e2406b52ad429470734ebd5                 1                    0
12  0006ec9db01a64e59a68b2c340bf65a7                 1                    0
13  0008288aa423d2a3f00fcb17cd7d8719                 2                    1
14  0008288aa423d2a3f00fcb17cd7d8719                 2                    1
  order_purchase_timestamp  purchase_year  purchase_month  \
0      2017-09-13 08:59:02           2017               9
1      2017-04-26 10:53:06           2017               4
2      2018-01-14 14:33:31           2018               1
3      2018-08-08 10:00:35           2018               8
4      2017-02-04 13:57:51           2017               2
5      2017-05-15 21:42:34           2017               5
6      2017-12-10 11:53:48           2017              12
7      2018-07-04 12:08:27           2018               7
8      2018-03-19 18:40:33           2018               3
9      2018-07-02 13:59:39           2018               7

   purchase_day_of_week
0                     2
1                     2
2                     6
3                     2
4                     5
5                     0
6                     6
7                     2
8                     0
9                     0
  order_purchase_timestamp  purchase_hour
0      2017-09-13 08:59:02              8
1      2017-04-26 10:53:06             10
2      2018-01-14 14:33:31             14
3      2018-08-08 10:00:35             10
4      2017-02-04 13:57:51             13
5      2017-05-15 21:42:34             21
6      2017-12-10 11:53:48             11
7      2018-07-04 12:08:27             12
8      2018-03-19 18:40:33             18
9      2018-07-02 13:59:39             13
    purchase_day_of_week  is_weekend
0                      2           0
1                      2           0
2                      6           1
3                      2           0
4                      5           1
5                      0           0
6                      6           1
7                      2           0
8                      0           0
9                      0           0
10                     5           1
11                     4           0
12                     1           0
13                     1           0
14                     1           0
  order_purchase_timestamp   order_approved_at  approval_days
0      2017-09-13 08:59:02 2017-09-13 09:45:35       0.032326
1      2017-04-26 10:53:06 2017-04-26 11:05:13       0.008414
2      2018-01-14 14:33:31 2018-01-14 14:48:30       0.010405
3      2018-08-08 10:00:35 2018-08-08 10:10:18       0.006748
4      2017-02-04 13:57:51 2017-02-04 14:10:13       0.008588
5      2017-05-15 21:42:34 2017-05-17 03:55:27       1.258947
6      2017-12-10 11:53:48 2017-12-10 12:10:31       0.011609
7      2018-07-04 12:08:27 2018-07-05 16:35:48       1.185660
8      2018-03-19 18:40:33 2018-03-20 18:35:21       0.996389
9      2018-07-02 13:59:39 2018-07-02 14:10:56       0.007836
    order_approved_at order_delivered_carrier_date  shipping_preparation_days
0 2017-09-13 09:45:35          2017-09-19 18:34:16                   6.367141
1 2017-04-26 11:05:13          2017-05-04 14:35:00                   8.145683
2 2018-01-14 14:48:30          2018-01-16 12:36:48                   1.908542
3 2018-08-08 10:10:18          2018-08-10 13:28:00                   2.137292
4 2017-02-04 14:10:13          2017-02-16 09:46:09                  11.816620
5 2017-05-17 03:55:27          2017-05-17 11:05:55                   0.298935
6 2017-12-10 12:10:31          2017-12-12 01:07:48                   1.539780
7 2018-07-05 16:35:48          2018-07-05 12:15:00                  -0.181111
8 2018-03-20 18:35:21          2018-03-28 00:37:42                   7.251632
9 2018-07-02 14:10:56          2018-07-03 14:25:00                   1.009769
  order_delivered_carrier_date order_delivered_customer_date  transit_days
0          2017-09-19 18:34:16           2017-09-20 23:43:48      1.214954
1          2017-05-04 14:35:00           2017-05-12 16:04:24      8.062083
2          2018-01-16 12:36:48           2018-01-22 13:19:16      6.029491
3          2018-08-10 13:28:00           2018-08-14 13:32:39      4.003229
4          2017-02-16 09:46:09           2017-03-01 16:42:31     13.289144
5          2017-05-17 11:05:55           2017-05-22 13:44:35      5.110185
6          2017-12-12 01:07:48           2017-12-18 22:03:38      6.872106
7          2018-07-05 12:15:00           2018-07-09 14:04:07      4.075775
8          2018-03-28 00:37:42           2018-03-29 18:17:31      1.735984
9          2018-07-03 14:25:00           2018-07-04 17:28:31      1.127442
    transit_days transit_speed
0       1.214954          Fast
1       8.062083          Slow
2       6.029491        Normal
3       4.003229        Normal
4      13.289144          Slow
5       5.110185        Normal
6       6.872106        Normal
7       4.075775        Normal
8       1.735984          Fast
9       1.127442          Fast
10      1.775972          Fast
11      7.961713          Slow
12      5.584896        Normal
13      5.813819        Normal
14      5.813819        Normal

Transit speed counts:
transit_speed
Slow       56235
Normal     34975
Fast       18799
Unknown     2641
Name: count, dtype: int64
   order_delivered_carrier_date order_delivered_customer_date delivery_status
0           2017-09-19 18:34:16           2017-09-20 23:43:48       Delivered
1           2017-05-04 14:35:00           2017-05-12 16:04:24       Delivered
2           2018-01-16 12:36:48           2018-01-22 13:19:16       Delivered
3           2018-08-10 13:28:00           2018-08-14 13:32:39       Delivered
4           2017-02-16 09:46:09           2017-03-01 16:42:31       Delivered
5           2017-05-17 11:05:55           2017-05-22 13:44:35       Delivered
6           2017-12-12 01:07:48           2017-12-18 22:03:38       Delivered
7           2018-07-05 12:15:00           2018-07-09 14:04:07       Delivered
8           2018-03-28 00:37:42           2018-03-29 18:17:31       Delivered
9           2018-07-03 14:25:00           2018-07-04 17:28:31       Delivered
10          2018-03-27 05:26:55           2018-03-29 00:04:19       Delivered
11          2018-07-30 14:52:00           2018-08-07 13:56:52       Delivered

## 3.2 Dataset Overview

In [2]:
# ============================================
# STEP 32.1 — FINAL DATASET OVERVIEW
# ============================================

print("========== DATASET OVERVIEW ==========")

print("Rows:", order_items_complete.shape[0])
print("Columns:", order_items_complete.shape[1])

print("\nDataset memory usage:")
print(
    f"{order_items_complete.memory_usage(deep=True).sum() / (1024**2):.2f} MB"
)

print("\n========== DATA TYPES ==========")
print(order_items_complete.dtypes.value_counts())

print("\n========== MISSING VALUES ==========")

missing_summary = (
    order_items_complete.isnull()
    .sum()
    .reset_index()
)

missing_summary.columns = ["column", "missing_count"]

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"]
    / len(order_items_complete)
    * 100
)

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
].sort_values(
    by="missing_count",
    ascending=False
)

print(missing_summary.to_string(index=False))

========== DATASET OVERVIEW ==========
Rows: 112650
Columns: 71

Dataset memory usage:
92.14 MB

========== DATA TYPES ==========
float64           28
int64             19
str               18
datetime64[us]     6
Name: count, dtype: int64

========== MISSING VALUES ==========
                       column  missing_count  missing_percentage
              review_comments          64237           57.023524
    shipping_preparation_days           2760            2.450067
                 transit_days           2691            2.388815
                delivery_days           2454            2.178429
          delivery_delay_days           2454            2.178429
order_delivered_customer_date           2454            2.178429
                   is_delayed           2454            2.178429
 order_delivered_carrier_date           1381            1.225921
            review_score_mean            942            0.836218
             review_score_min            942            0.836218
           review_score_count            942            0.836218
  seller_customer_distance_km            554            0.491789
           customer_longitude            302            0.268087
            customer_latitude            302            0.268087
             seller_longitude            253            0.224589
              seller_latitude            253            0.224589
            order_approved_at             15            0.013316
                approval_days             15            0.013316

## 2. EDA Analysis

In [3]:
# ============================================
# STEP 32.2 — ORDER STATUS ANALYSIS
# ============================================

import matplotlib.pyplot as plt

# Count orders by status
order_status_counts = (
    order_items_complete["order_status"]
    .value_counts()
)

print("========== ORDER STATUS COUNTS ==========")
print(order_status_counts)

print("\n========== ORDER STATUS PERCENTAGE ==========")

order_status_percentage = (
    order_status_counts
    / order_status_counts.sum()
    * 100
)

print(order_status_percentage.round(2))

========== ORDER STATUS COUNTS ==========
order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

========== ORDER STATUS PERCENTAGE ==========
order_status
delivered      97.82
shipped         1.05
canceled        0.48
invoiced        0.32
processing      0.32
unavailable     0.01
approved        0.00
Name: count, dtype: float64

## 3. EDA Analysis

In [4]:
# ============================================
# STEP 32.3 — DELIVERY PERFORMANCE ANALYSIS
# ============================================

print("========== DELIVERY DAYS SUMMARY ==========")

print(
    order_items_complete["delivery_days"]
    .describe()
)

print("\n========== ESTIMATED DELIVERY DAYS SUMMARY ==========")

print(
    order_items_complete["estimated_delivery_days"]
    .describe()
)

print("\n========== DELIVERY DELAY SUMMARY ==========")

print(
    order_items_complete["delivery_delay_days"]
    .describe()
)

print("\n========== DELAY STATUS ==========")

print(
    order_items_complete["is_delayed"]
    .value_counts(dropna=False)
)

========== DELIVERY DAYS SUMMARY ==========
count    110196.000000
mean         12.007723
std           9.451455
min           0.000000
25%           6.000000
50%          10.000000
75%          15.000000
max         209.000000
Name: delivery_days, dtype: float64

========== ESTIMATED DELIVERY DAYS SUMMARY ==========
count    112650.000000
mean         23.470484
std           8.884872
min           2.000000
25%          18.000000
50%          23.000000
75%          28.000000
max         155.000000
Name: estimated_delivery_days, dtype: float64

========== DELIVERY DELAY SUMMARY ==========
count    110196.000000
mean        -12.030201
std          10.160157
min        -147.000000
25%         -17.000000
50%         -13.000000
75%          -7.000000
max         188.000000
Name: delivery_delay_days, dtype: float64

========== DELAY STATUS ==========
is_delayed
0.0    102931
1.0      7265
NaN      2454
Name: count, dtype: int64

## 4. EDA Analysis

In [5]:
# ============================================
# STEP 32.4 — DELIVERY DELAY ANALYSIS
# ============================================

# Separate valid delivery delay values
delay_data = order_items_complete[
    order_items_complete["delivery_delay_days"].notna()
]["delivery_delay_days"]

print("========== EARLY / ON-TIME / DELAYED ==========")

print(
    "Early delivery:",
    (delay_data < 0).sum()
)

print(
    "On estimated date:",
    (delay_data == 0).sum()
)

print(
    "Delayed:",
    (delay_data > 0).sum()
)

print("\n========== DELAY PERCENTAGE ==========")

total_valid = len(delay_data)

print(
    f"Early delivery: {(delay_data < 0).sum() / total_valid * 100:.2f}%"
)

print(
    f"On estimated date: {(delay_data == 0).sum() / total_valid * 100:.2f}%"
)

print(
    f"Delayed: {(delay_data > 0).sum() / total_valid * 100:.2f}%"
)

print("\n========== ACTUAL DELAY ONLY ==========")

actual_delays = delay_data[delay_data > 0]

print(actual_delays.describe())

========== EARLY / ON-TIME / DELAYED ==========
Early delivery: 101481
On estimated date: 1450
Delayed: 7265

========== DELAY PERCENTAGE ==========
Early delivery: 92.09%
On estimated date: 1.32%
Delayed: 6.59%

========== ACTUAL DELAY ONLY ==========
count    7265.000000
mean       10.488782
std        14.499579
min         1.000000
25%         3.000000
50%         7.000000
75%        13.000000
max       188.000000
Name: delivery_delay_days, dtype: float64

## 5. EDA Analysis

In [6]:
# ============================================
# STEP 32.5 — REVIEW SCORE ANALYSIS
# ============================================

print("========== REVIEW SCORE COUNTS ==========")

review_score_counts = (
    order_items_complete["review_score_mean"]
    .value_counts()
    .sort_index()
)

print(review_score_counts)

print("\n========== REVIEW SCORE PERCENTAGE ==========")

review_score_percentage = (
    review_score_counts
    / review_score_counts.sum()
    * 100
)

print(review_score_percentage.round(2))

print("\n========== REVIEW SCORE SUMMARY ==========")

print(
    order_items_complete["review_score_mean"]
    .describe()
)

========== REVIEW SCORE COUNTS ==========
review_score_mean
1.000000    14079
1.500000       18
2.000000     3833
2.500000       45
3.000000     9384
3.333333        1
3.500000       31
4.000000    21166
4.333333        1
4.500000       68
5.000000    63082
Name: count, dtype: int64

========== REVIEW SCORE PERCENTAGE ==========
review_score_mean
1.000000    12.60
1.500000     0.02
2.000000     3.43
2.500000     0.04
3.000000     8.40
3.333333     0.00
3.500000     0.03
4.000000    18.95
4.333333     0.00
4.500000     0.06
5.000000    56.47
Name: count, dtype: float64

========== REVIEW SCORE SUMMARY ==========
count    111708.000000
mean          4.033128
std           1.386119
min           1.000000
25%           4.000000
50%           5.000000
75%           5.000000
max           5.000000
Name: review_score_mean, dtype: float64

## 6. EDA Analysis

In [7]:
# ============================================
# STEP 32.6 — REVIEW SCORE VS DELIVERY DELAY
# ============================================

# Create a simple review group
order_items_complete["review_group"] = pd.cut(
    order_items_complete["review_score_mean"],
    bins=[0, 2, 3, 4, 5],
    labels=[
        "Low (1-2)",
        "Average (3)",
        "Good (4)",
        "Excellent (5)"
    ],
    include_lowest=True
)

print("========== REVIEW GROUP COUNTS ==========")

print(
    order_items_complete["review_group"]
    .value_counts()
    .sort_index()
)

print("\n========== AVERAGE DELIVERY DELAY BY REVIEW GROUP ==========")

review_delay_analysis = (
    order_items_complete
    .groupby("review_group", observed=True)
    .agg(
        order_items=("order_id", "count"),
        average_delay_days=("delivery_delay_days", "mean"),
        median_delay_days=("delivery_delay_days", "median"),
        delayed_items=("is_delayed", "sum")
    )
)

review_delay_analysis["delayed_percentage"] = (
    review_delay_analysis["delayed_items"]
    / review_delay_analysis["order_items"]
    * 100
)

print(
    review_delay_analysis.round(2)
)

========== REVIEW GROUP COUNTS ==========
review_group
Low (1-2)        17930
Average (3)       9429
Good (4)         21198
Excellent (5)    63151
Name: count, dtype: int64

========== AVERAGE DELIVERY DELAY BY REVIEW GROUP ==========
               order_items  average_delay_days  median_delay_days  \
review_group
Low (1-2)            17930               -6.79               -9.0
Average (3)           9429              -11.08              -11.0
Good (4)             21198              -12.48              -12.0
Excellent (5)        63151              -13.42              -13.0

               delayed_items  delayed_percentage
review_group
Low (1-2)             4454.0               24.84
Average (3)            752.0                7.98
Good (4)               708.0                3.34
Excellent (5)         1170.0                1.85

## 7. EDA Analysis

In [8]:
# ============================================
# STEP 32.7 — REMOVE TEMPORARY EDA COLUMN
# ============================================

if "review_group" in order_items_complete.columns:
    order_items_complete.drop(
        columns=["review_group"],
        inplace=True
    )

print("review_group removed successfully.")

print("\nCurrent dataset shape:")
print(order_items_complete.shape)

review_group removed successfully.

Current dataset shape:
(112650, 71)

## 8. EDA Analysis

In [9]:
# ============================================
# STEP 32.8 — PRODUCT CATEGORY ANALYSIS
# ============================================

print("========== PRODUCT CATEGORY OVERVIEW ==========")

# Number of unique product categories
unique_categories = (
    order_items_complete["product_category_name_english"]
    .nunique()
)

print("Number of unique product categories:", unique_categories)

# Count order items by category
category_counts = (
    order_items_complete["product_category_name_english"]
    .value_counts()
)

print("\n========== TOP 20 PRODUCT CATEGORIES ==========")
print(category_counts.head(20))

# Percentage of order items
category_percentage = (
    category_counts
    / len(order_items_complete)
    * 100
)

print("\n========== TOP 20 CATEGORY PERCENTAGES ==========")
print(category_percentage.head(20).round(2))

========== PRODUCT CATEGORY OVERVIEW ==========
Number of unique product categories: 74

========== TOP 20 PRODUCT CATEGORIES ==========
product_category_name_english
bed_bath_table              11115
health_beauty                9670
sports_leisure               8641
furniture_decor              8334
computers_accessories        7827
housewares                   6964
watches_gifts                5991
telephony                    4545
garden_tools                 4347
auto                         4235
toys                         4117
cool_stuff                   3796
perfumery                    3419
baby                         3065
electronics                  2767
stationery                   2517
fashion_bags_accessories     2031
pet_shop                     1947
office_furniture             1691
Unknown                      1603
Name: count, dtype: int64

========== TOP 20 CATEGORY PERCENTAGES ==========
product_category_name_english
bed_bath_table              9.87
health_beauty               8.58
sports_leisure              7.67
furniture_decor             7.40
computers_accessories       6.95
housewares                  6.18
watches_gifts               5.32
telephony                   4.03
garden_tools                3.86
auto                        3.76
toys                        3.65
cool_stuff                  3.37
perfumery                   3.04
baby                        2.72
electronics                 2.46
stationery                  2.23
fashion_bags_accessories    1.80
pet_shop                    1.73
office_furniture            1.50
Unknown                     1.42
Name: count, dtype: float64

## 9. EDA Analysis

In [10]:
# ============================================
# STEP 32.9 — CATEGORY VS CUSTOMER EXPERIENCE
# ============================================

category_experience = (
    order_items_complete
    .groupby("product_category_name_english", observed=True)
    .agg(
        order_items=("order_id", "count"),
        average_review_score=("review_score_mean", "mean"),
        delayed_items=("is_delayed", "sum"),
        average_delivery_days=("delivery_days", "mean")
    )
    .reset_index()
)

# Calculate delay percentage
category_experience["delayed_percentage"] = (
    category_experience["delayed_items"]
    / category_experience["order_items"]
    * 100
)

# Sort by number of orders
category_experience = category_experience.sort_values(
    by="order_items",
    ascending=False
)

print("========== CATEGORY VS CUSTOMER EXPERIENCE ==========")
print(
    category_experience
    .head(20)
    .round(2)
    .to_string(index=False)
)

print("\n========== CATEGORIES WITH HIGHEST DELAY PERCENTAGE ==========")

# Only consider categories with at least 100 order items
reliable_delay_categories = category_experience[
    category_experience["order_items"] >= 100
]

print(
    reliable_delay_categories
    .sort_values(
        by="delayed_percentage",
        ascending=False
    )
    .head(15)
    .round(2)
    .to_string(index=False)
)

========== CATEGORY VS CUSTOMER EXPERIENCE ==========
product_category_name_english  order_items  average_review_score  delayed_items  average_delivery_days  delayed_percentage
               bed_bath_table        11115                  3.90          770.0                  12.34                6.93
                health_beauty         9670                  4.14          717.0                  11.52                7.41
               sports_leisure         8641                  4.11          532.0                  11.69                6.16
              furniture_decor         8334                  3.91          574.0                  12.40                6.89
        computers_accessories         7827                  3.93          496.0                  12.78                6.34
                   housewares         6964                  4.05          340.0                  10.46                4.88
                watches_gifts         5991                  4.02          422.0                  12.19                7.04
                    telephony         4545                  3.95          308.0                  12.38                6.78
                 garden_tools         4347                  4.05          280.0                  13.23                6.44
                         auto         4235                  4.06          291.0                  11.77                6.87
                         toys         4117                  4.16          256.0                  11.23                6.22
                   cool_stuff         3796                  4.15          217.0                  11.90                5.72
                    perfumery         3419                  4.17          217.0                  11.28                6.35
                         baby         3065                  4.01          229.0                  12.06                7.47
                  electronics         2767                  4.04          207.0                  12.42                7.48
                   stationery         2517                  4.20          167.0                  12.28                6.63
     fashion_bags_accessories         2031                  4.15          105.0                  10.62                5.17
                     pet_shop         1947                  4.18           95.0                  10.76                4.88
             office_furniture         1691                  3.49          133.0                  20.39                7.87
                      Unknown         1603                  3.84          115.0                  12.31                7.17

========== CATEGORIES WITH HIGHEST DELAY PERCENTAGE ==========
product_category_name_english  order_items  average_review_score  delayed_items  average_delivery_days  delayed_percentage
                        audio          364                  3.83           42.0                  12.88               11.54
           christmas_supplies          153                  4.02           15.0                  15.30                9.80
                 home_confort          434                  3.83           40.0                  13.04                9.22
      fashion_underwear_beach          131                  3.98           12.0                  13.28                9.16
             office_furniture         1691                  3.49          133.0                  20.39                7.87
              books_technical          267                  4.36           21.0                  10.23                7.87
                  electronics         2767                  4.04          207.0                  12.42                7.48
                         baby         3065                  4.01          229.0                  12.06                7.47
                health_beauty         9670                  4.14          717.0                  11.52                7.41
    construction_tools_lights          304                  4.05           22.0                   9.25                7.24
                      Unknown         1603                  3.84          115.0                  12.31                7.17
          musical_instruments          680                  4.15           48.0                  12.50                7.06
                watches_gifts         5991                  4.02          422.0                  12.19                7.04
        furniture_living_room          503                  3.90           35.0                  13.29                6.96
               bed_bath_table        11115                  3.90          770.0                  12.34                6.93

## 10. EDA Analysis

In [11]:
# ============================================
# STEP 32.10 — SELLER PERFORMANCE ANALYSIS
# ============================================

seller_performance = (
    order_items_complete
    .groupby("seller_id")
    .agg(
        order_items=("order_id", "count"),
        average_review_score=("review_score_mean", "mean"),
        delayed_items=("is_delayed", "sum"),
        average_delivery_days=("delivery_days", "mean"),
        average_freight_value=("freight_value", "mean")
    )
    .reset_index()
)

# Calculate delay percentage
seller_performance["delayed_percentage"] = (
    seller_performance["delayed_items"]
    / seller_performance["order_items"]
    * 100
)

print("========== SELLER PERFORMANCE OVERVIEW ==========")
print("Number of sellers:", len(seller_performance))

print("\n========== TOP 15 SELLERS BY ORDER VOLUME ==========")
print(
    seller_performance
    .sort_values("order_items", ascending=False)
    .head(15)
    .round(2)
    .to_string(index=False)
)

# Avoid unreliable percentages from sellers with very few orders
reliable_sellers = seller_performance[
    seller_performance["order_items"] >= 50
]

print("\n========== TOP 15 SELLERS BY DELAY PERCENTAGE ==========")
print(
    reliable_sellers
    .sort_values("delayed_percentage", ascending=False)
    .head(15)
    .round(2)
    .to_string(index=False)
)

print("\n========== SELLERS WITH LOWEST REVIEW SCORES ==========")
print(
    reliable_sellers
    .sort_values("average_review_score", ascending=True)
    .head(15)
    .round(2)
    .to_string(index=False)
)

========== SELLER PERFORMANCE OVERVIEW ==========
Number of sellers: 3095

========== TOP 15 SELLERS BY ORDER VOLUME ==========
                       seller_id  order_items  average_review_score  delayed_items  average_delivery_days  average_freight_value  delayed_percentage
6560211a19b47992c3666cc44a7e94c0         2033                  3.91          102.0                   9.06                  13.75                5.02
4a3ca9315b744ce9f8e9374361493884         1987                  3.80          189.0                  13.94                  17.65                9.51
1f50f920176fa81dab994f9023523100         1931                  3.99          150.0                  15.11                  18.21                7.77
cc419e0650a3c5ba77189a1882b7556a         1775                  4.07           88.0                  11.06                  14.46                4.96
da8622b14eb17ae2831f4ac5b9dab84a         1551                  4.06           99.0                  10.70                  16.09                6.38
955fee9216a65b617aa5c0531780ce60         1499                  4.05           95.0                  10.30                  16.97                6.34
1025f0e2d44d7041d6cf58b6550e0bfa         1428                  3.85           95.0                  11.57                  23.73                6.65
7c67e1448b00f6e969d365cea6b010ab         1364                  3.34          120.0                  21.95                  37.84                8.80
ea8482cd71df3c1969d7b9473ff13abc         1203                  3.95          100.0                  12.85                  14.58                8.31
7a67c85e85bb2ce8582c35f2203ad736         1171                  4.23           60.0                  10.69                  17.85                5.12
4869f7a5dfa277a7dca6462dcf3b52b2         1156                  4.12          121.0                  14.55                  17.45               10.47
3d871de0142ce09b7081e2b9d1733cb1         1147                  4.11           62.0                  12.96                  19.56                5.41
8b321bb669392f5163d04c59e235e066         1018                  4.00           87.0                  12.17                  13.91                8.55
cca3071e3e9bb7d12640c9fbe2301306          830                  3.85           37.0                  13.75                  17.31                4.46
620c87c171fb2a6dd6e8bb4dec959fc6          798                  4.21           65.0                  12.43                  17.71                8.15

========== TOP 15 SELLERS BY DELAY PERCENTAGE ==========
                       seller_id  order_items  average_review_score  delayed_items  average_delivery_days  average_freight_value  delayed_percentage
54965bbe3e4f07ae045b90b0b8541f52           86                  2.94           26.0                  26.23                  25.62               30.23
ede0c03645598cdfc63ca8237acbe73d           50                  3.62           15.0                  18.04                  15.03               30.00
2a1348e9addc1af5aaa619b1a3679d6b           55                  3.00           15.0                  26.78                  14.33               27.27
835f0f7810c76831d6c7d24c7a646d4d           50                  3.30           13.0                  18.04                  19.28               26.00
bbad7e518d7af88a0897397ffdca1979           85                  3.04           19.0                  14.79                  15.74               22.35
beadbee30901a7f61d031b6b686095ad           68                  3.94           15.0                  13.06                  13.79               22.06
6039e27294dc75811c0d8a39069f52c0           75                  3.83           16.0                  17.47                  31.69               21.33
a49928bcdf77c55c6d6e05e09a9b4ca5          106                  2.95           22.0                  16.52                  16.58               20.75
712e6ed8aa4aa1fa65dab41fed5737e4           87                  3.45           17.0                  23.39                  79.19               19.54
2a261b5b644fa05f4f2700eb93544f2c           82                  3.35           16.0                  14.04                  24.90               19.51
602044f2c16190c2c6e45eb35c2e21cb           57                  2.96           11.0                  15.35                  16.46               19.30
06a2c3af7b3aee5d69171b0e14f0ee87          405                  4.00           78.0                  17.27                  29.98               19.26
ea566164622c6b439516ab18062c42cd           52                  3.75           10.0                  13.81                  16.51               19.23
0d85bbda9889ce1f7e63778d24f346eb           58                  4.21           11.0                  17.79                  28.01               18.97
cac4c8e7b1ca6252d8f20b2fc1a2e4af           83                  3.53           15.0                  19.43                  18.73               18.07

========== SELLERS WITH LOWEST REVIEW SCORES ==========
                       seller_id  order_items  average_review_score  delayed_items  average_delivery_days  average_freight_value  delayed_percentage
1ca7077d890b907f89be8c954a02686a          137                  2.20           19.0                  14.51                  12.12               13.87
2eb70248d66e0e3ef83659f71b244378          212                  2.71           23.0                  17.51                  15.24               10.85
54965bbe3e4f07ae045b90b0b8541f52           86                  2.94           26.0                  26.23                  25.62               30.23
a49928bcdf77c55c6d6e05e09a9b4ca5          106                  2.95           22.0                  16.52                  16.58               20.75
602044f2c16190c2c6e45eb35c2e21cb           57                  2.96           11.0                  15.35                  16.46               19.30
972d0f9cf61b499a4812cf0bfa3ad3c4           88                  2.96           10.0                  17.76                  24.45               11.36
8e6d7754bc7e0f22c96d255ebda59eba          130                  2.97           13.0                  13.57                  13.19               10.00
2a1348e9addc1af5aaa619b1a3679d6b           55                  3.00           15.0                  26.78                  14.33               27.27
bbad7e518d7af88a0897397ffdca1979           85                  3.04           19.0                  14.79                  15.74               22.35
8444e55c1f13cd5c179851e5ca5ebd00          109                  3.07           11.0                  20.78                  19.06               10.09
5058e8c1e82653974541e83690655b4a           78                  3.08            8.0                  25.94                  39.17               10.26
e7d5b006eb624f13074497221eb37807           63                  3.11            2.0                  10.54                  11.77                3.17
dc8798cbf453b7e0f98745e396cc5616           51                  3.15            3.0                  13.07                  12.24                5.88
95f83f51203c626648c875dd41874c7f           67                  3.21            2.0                  10.69                  24.02                2.99
835f0f7810c76831d6c7d24c7a646d4d           50                  3.30           13.0                  18.04                  19.28               26.00

## 11. EDA Analysis

In [12]:
# ============================================
# STEP 32.11 — PRICE & FREIGHT ANALYSIS
# ============================================

print("========== PRICE SUMMARY ==========")
print(order_items_complete["price"].describe().round(2))

print("\n========== FREIGHT VALUE SUMMARY ==========")
print(order_items_complete["freight_value"].describe().round(2))

print("\n========== FREIGHT TO PRICE RATIO ==========")
print(
    order_items_complete["freight_to_price_ratio"]
    .describe()
    .round(2)
)

print("\n========== HIGH FREIGHT RATIO ==========")
print(
    order_items_complete["high_freight_ratio"]
    .value_counts()
)

print("\n========== HIGH FREIGHT RATIO PERCENTAGE ==========")
print(
    (
        order_items_complete["high_freight_ratio"]
        .value_counts(normalize=True)
        * 100
    ).round(2)
)

# Compare delivery delay by freight ratio group
freight_analysis = (
    order_items_complete
    .groupby("high_freight_ratio", observed=True)
    .agg(
        order_items=("order_id", "count"),
        average_price=("price", "mean"),
        average_freight=("freight_value", "mean"),
        average_freight_ratio=("freight_to_price_ratio", "mean"),
        average_delivery_days=("delivery_days", "mean"),
        delayed_items=("is_delayed", "sum")
    )
)

freight_analysis["delayed_percentage"] = (
    freight_analysis["delayed_items"]
    / freight_analysis["order_items"]
    * 100
)

print("\n========== FREIGHT RATIO VS DELIVERY ==========")
print(freight_analysis.round(2))

========== PRICE SUMMARY ==========
count    112650.00
mean        120.65
std         183.63
min           0.85
25%          39.90
50%          74.99
75%         134.90
max        6735.00
Name: price, dtype: float64

========== FREIGHT VALUE SUMMARY ==========
count    112650.00
mean         19.99
std          15.81
min           0.00
25%          13.08
50%          16.26
75%          21.15
max         409.68
Name: freight_value, dtype: float64

========== FREIGHT TO PRICE RATIO ==========
count    112650.00
mean          0.32
std           0.35
min           0.00
25%           0.13
50%           0.23
75%           0.39
max          26.24
Name: freight_to_price_ratio, dtype: float64

========== HIGH FREIGHT RATIO ==========
high_freight_ratio
0    93706
1    18944
Name: count, dtype: int64

========== HIGH FREIGHT RATIO PERCENTAGE ==========
high_freight_ratio
0    83.18
1    16.82
Name: proportion, dtype: float64

========== FREIGHT RATIO VS DELIVERY ==========
                    order_items  average_price  average_freight  \
high_freight_ratio
0                         93706         138.97            19.53
1                         18944          30.04            22.25

                    average_freight_ratio  average_delivery_days  \
high_freight_ratio
0                                    0.21                  11.76
1                                    0.85                  13.25

                    delayed_items  delayed_percentage
high_freight_ratio
0                          5975.0                6.38
1                          1290.0                6.81

## 12. EDA Analysis

In [13]:
# ============================================
# STEP 32.12 — DISTANCE & LOGISTICS ANALYSIS
# ============================================

print("========== DISTANCE SUMMARY ==========")

print(
    order_items_complete["seller_customer_distance_km"]
    .describe()
    .round(2)
)

print("\n========== DISTANCE CATEGORY COUNTS ==========")

distance_counts = (
    order_items_complete["distance_category"]
    .value_counts()
)

print(distance_counts)

print("\n========== DISTANCE CATEGORY PERCENTAGE ==========")

print(
    (
        distance_counts
        / len(order_items_complete)
        * 100
    ).round(2)
)

# Compare logistics performance by distance category
distance_analysis = (
    order_items_complete
    .groupby("distance_category", observed=True)
    .agg(
        order_items=("order_id", "count"),
        average_distance_km=("seller_customer_distance_km", "mean"),
        average_delivery_days=("delivery_days", "mean"),
        delayed_items=("is_delayed", "sum"),
        average_freight=("freight_value", "mean"),
        average_review_score=("review_score_mean", "mean")
    )
    .reset_index()
)

distance_analysis["delayed_percentage"] = (
    distance_analysis["delayed_items"]
    / distance_analysis["order_items"]
    * 100
)

print("\n========== DISTANCE VS LOGISTICS ==========")

print(
    distance_analysis
    .round(2)
    .to_string(index=False)
)

========== DISTANCE SUMMARY ==========
count    112096.00
mean        597.00
std         590.04
min           0.00
25%         184.11
50%         431.75
75%         792.25
max        8677.92
Name: seller_customer_distance_km, dtype: float64

========== DISTANCE CATEGORY COUNTS ==========
distance_category
Very Far    38564
Far         36958
Near        20993
Medium      15581
Unknown       554
Name: count, dtype: int64

========== DISTANCE CATEGORY PERCENTAGE ==========
distance_category
Very Far    34.23
Far         32.81
Near        18.64
Medium      13.83
Unknown      0.49
Name: count, dtype: float64

========== DISTANCE VS LOGISTICS ==========
distance_category  order_items  average_distance_km  average_delivery_days  delayed_items  average_freight  average_review_score  delayed_percentage
              Far        36958               430.09                  12.07         2347.0            19.57                  4.00                6.35
           Medium        15581               200.50                   9.44          768.0            16.40                  4.14                4.93
             Near        20993                39.91                   6.07          914.0            11.76                  4.16                4.35
          Unknown          554                  NaN                  13.74           46.0            21.50                  4.03                8.30
         Very Far        38564              1220.41                  16.19         3190.0            26.30                  3.96                8.27

## 13. EDA Analysis

In [14]:
# ============================================
# STEP 32.13 — TRANSIT SPEED ANALYSIS
# ============================================

transit_analysis = (
    order_items_complete
    .groupby("transit_speed", observed=True)
    .agg(
        order_items=("order_id", "count"),
        average_transit_days=("transit_days", "mean"),
        average_review_score=("review_score_mean", "mean"),
        delayed_items=("is_delayed", "sum"),
        average_delivery_days=("delivery_days", "mean")
    )
    .reset_index()
)

transit_analysis["delayed_percentage"] = (
    transit_analysis["delayed_items"]
    / transit_analysis["order_items"]
    * 100
)

print("========== TRANSIT SPEED DISTRIBUTION ==========")

print(
    order_items_complete["transit_speed"]
    .value_counts()
)

print("\n========== TRANSIT SPEED VS CUSTOMER EXPERIENCE ==========")

print(
    transit_analysis
    .round(2)
    .to_string(index=False)
)

========== TRANSIT SPEED DISTRIBUTION ==========
transit_speed
Slow       56235
Normal     34975
Fast       18749
Unknown     2691
Name: count, dtype: int64

========== TRANSIT SPEED VS CUSTOMER EXPERIENCE ==========
transit_speed  order_items  average_transit_days  average_review_score  delayed_items  average_delivery_days  delayed_percentage
         Fast        18749                  1.66                  4.30          253.0                   4.45                1.35
       Normal        34975                  5.08                  4.23          408.0                   7.76                1.17
         Slow        56235                 14.27                  3.92         6601.0                  17.19               11.74
      Unknown         2691                   NaN                  1.95            3.0                   6.80                0.11

## 14. EDA Analysis

In [15]:
# ============================================
# STEP 32.14 — MULTI-ITEM & ORDER VALUE ANALYSIS
# ============================================

order_type_analysis = (
    order_items_complete
    .groupby("is_multi_item_order", observed=True)
    .agg(
        order_items=("order_id", "count"),
        average_order_item_count=("order_item_count", "mean"),
        average_order_total_value=("order_total_value", "mean"),
        average_delivery_days=("delivery_days", "mean"),
        average_review_score=("review_score_mean", "mean"),
        delayed_items=("is_delayed", "sum")
    )
    .reset_index()
)

order_type_analysis["delayed_percentage"] = (
    order_type_analysis["delayed_items"]
    / order_type_analysis["order_items"]
    * 100
)

print("========== SINGLE VS MULTI-ITEM ORDERS ==========")

print(
    order_type_analysis
    .round(2)
    .to_string(index=False)
)

print("\n========== ORDER ITEM COUNT SUMMARY ==========")

print(
    order_items_complete["order_item_count"]
    .describe()
    .round(2)
)

print("\n========== ORDER TOTAL VALUE SUMMARY ==========")

print(
    order_items_complete["order_total_value"]
    .describe()
    .round(2)
)

========== SINGLE VS MULTI-ITEM ORDERS ==========
 is_multi_item_order  order_items  average_order_item_count  average_order_total_value  average_delivery_days  average_review_score  delayed_items  delayed_percentage
                   0        88863                      1.00                     150.75                  12.18                  4.16         6025.0                6.78
                   1        23787                      2.87                     290.44                  11.39                  3.55         1240.0                5.21

========== ORDER ITEM COUNT SUMMARY ==========
count    112650.00
mean          1.40
std           1.12
min           1.00
25%           1.00
50%           1.00
75%           1.00
max          21.00
Name: order_item_count, dtype: float64

========== ORDER TOTAL VALUE SUMMARY ==========
count    112650.00
mean        180.24
std         272.83
min           9.59
25%          65.62
50%         114.44
75%         195.34
max       13664.08
Name: order_total_value, dtype: float64

## 15. EDA Analysis

In [16]:
# ============================================
# STEP 32.15 — CORRELATION & FEATURE RELATIONSHIPS
# ============================================

numeric_features = [
    "price",
    "freight_value",
    "delivery_days",
    "estimated_delivery_days",
    "delivery_delay_days",
    "payment_total_value",
    "order_item_count",
    "order_total_value",
    "approval_days",
    "shipping_preparation_days",
    "transit_days",
    "seller_customer_distance_km",
    "freight_to_price_ratio",
    "product_volume_cm3",
    "review_score_mean"
]

correlation_matrix = (
    order_items_complete[numeric_features]
    .corr()
)

print("========== CORRELATION WITH DELIVERY DELAY ==========")

print(
    correlation_matrix["delivery_delay_days"]
    .sort_values(ascending=False)
    .round(3)
)

print("\n========== CORRELATION WITH REVIEW SCORE ==========")

print(
    correlation_matrix["review_score_mean"]
    .sort_values(ascending=False)
    .round(3)
)

========== CORRELATION WITH DELIVERY DELAY ==========
delivery_delay_days            1.000
delivery_days                  0.597
transit_days                   0.571
shipping_preparation_days      0.193
approval_days                  0.042
product_volume_cm3             0.012
price                         -0.004
order_total_value             -0.021
payment_total_value           -0.021
freight_to_price_ratio        -0.029
order_item_count              -0.035
freight_value                 -0.040
seller_customer_distance_km   -0.077
review_score_mean             -0.229
estimated_delivery_days       -0.511
Name: delivery_delay_days, dtype: float64

========== CORRELATION WITH REVIEW SCORE ==========
review_score_mean              1.000
price                         -0.004
approval_days                 -0.026
product_volume_cm3            -0.031
freight_value                 -0.036
freight_to_price_ratio        -0.037
seller_customer_distance_km   -0.053
estimated_delivery_days       -0.064
order_total_value             -0.085
payment_total_value           -0.085
shipping_preparation_days     -0.152
order_item_count              -0.164
delivery_delay_days           -0.229
transit_days                  -0.270
delivery_days                 -0.305
Name: review_score_mean, dtype: float64

## 3.16 Return and Complaint Analysis

### Part 1

In [17]:
# ============================================
# STEP 32.16 — RETURN & COMPLAINT ANALYSIS
# PART 1: NCH COMPLAINT DATA INSPECTION
# ============================================

print("========== NCH COMPLAINT DATA ==========")

print("\nShape:")
print(df_complaints_clean.shape)

print("\nColumns:")
print(df_complaints_clean.columns.tolist())

print("\nData:")
print(
    df_complaints_clean.to_string(index=False)
)

print("\nData Types:")
print(
    df_complaints_clean.dtypes
)

========== NCH COMPLAINT DATA ==========

Shape:
(11, 3)

Columns:
['Sl. No.', 'Nature of Grievances', 'Number of Grievances Received on NCH']

Data:
 Sl. No.                              Nature of Grievances  Number of Grievances Received on NCH
       1                            Deficiency in Services                                 59723
       2                         Delivery of Wrong Product                                 54563
       3            Delivery of Defective / Damage Product                                 53285
       4                          Paid amount not refunded                                 50997
       5                           Non-Delivery of Product                                 42781
       6                      Delay in Delivery of Product                                 27394
       7 Replacement / Refund not provided - As per policy                                 19020
       8    Amount Debited but Not Credited to Beneficiary                                 15315
       9             Product / Product Accessories Missing                                 15077
      10                    Account Blocked/Service Barred                                  5913
      11                                            Others                                 53265

Data Types:
Sl. No.                                 int64
Nature of Grievances                      str
Number of Grievances Received on NCH    int64
dtype: object

### Part 2

In [18]:
# ============================================
# STEP 32.16 — RETURN & COMPLAINT ANALYSIS
# PART 2: COMPLAINT DISTRIBUTION
# ============================================

complaint_analysis = df_complaints_clean.copy()

# Calculate total grievances
total_grievances = complaint_analysis[
    "Number of Grievances Received on NCH"
].sum()

# Calculate percentage
complaint_analysis["grievance_percentage"] = (
    complaint_analysis["Number of Grievances Received on NCH"]
    / total_grievances
    * 100
)

# Sort by number of grievances
complaint_analysis = complaint_analysis.sort_values(
    by="Number of Grievances Received on NCH",
    ascending=False
).reset_index(drop=True)

print("========== TOTAL GRIEVANCES ==========")
print(f"Total: {total_grievances:,}")

print("\n========== COMPLAINT DISTRIBUTION ==========")

print(
    complaint_analysis[
        [
            "Nature of Grievances",
            "Number of Grievances Received on NCH",
            "grievance_percentage"
        ]
    ]
    .round(2)
    .to_string(index=False)
)

========== TOTAL GRIEVANCES ==========
Total: 397,333

========== COMPLAINT DISTRIBUTION ==========
                             Nature of Grievances  Number of Grievances Received on NCH  grievance_percentage
                           Deficiency in Services                                 59723                 15.03
                        Delivery of Wrong Product                                 54563                 13.73
           Delivery of Defective / Damage Product                                 53285                 13.41
                                           Others                                 53265                 13.41
                         Paid amount not refunded                                 50997                 12.83
                          Non-Delivery of Product                                 42781                 10.77
                     Delay in Delivery of Product                                 27394                  6.89
Replacement / Refund not provided - As per policy                                 19020                  4.79
   Amount Debited but Not Credited to Beneficiary                                 15315                  3.85
            Product / Product Accessories Missing                                 15077                  3.79
                   Account Blocked/Service Barred                                  5913                  1.49

### Part 3

In [19]:
# ============================================
# STEP 32.16 — RETURN & COMPLAINT ANALYSIS
# PART 3: RETURNIQ-RELEVANT CATEGORIES
# ============================================

returniq_categories = [
    "Delivery of Wrong Product",
    "Delivery of Defective / Damage Product",
    "Non-Delivery of Product",
    "Delay in Delivery of Product",
    "Replacement / Refund not provided - As per policy",
    "Product / Product Accessories Missing"
]

refund_categories = [
    "Paid amount not refunded",
    "Replacement / Refund not provided - As per policy"
]

delivery_categories = [
    "Delivery of Wrong Product",
    "Delivery of Defective / Damage Product",
    "Non-Delivery of Product",
    "Delay in Delivery of Product",
    "Product / Product Accessories Missing"
]

# Total grievances
total_grievances = (
    df_complaints_clean[
        "Number of Grievances Received on NCH"
    ].sum()
)

# ReturnIQ-related grievances
returniq_total = (
    df_complaints_clean[
        df_complaints_clean["Nature of Grievances"]
        .isin(returniq_categories)
    ]["Number of Grievances Received on NCH"]
    .sum()
)

# Refund/replacement grievances
refund_total = (
    df_complaints_clean[
        df_complaints_clean["Nature of Grievances"]
        .isin(refund_categories)
    ]["Number of Grievances Received on NCH"]
    .sum()
)

# Delivery/product grievances
delivery_total = (
    df_complaints_clean[
        df_complaints_clean["Nature of Grievances"]
        .isin(delivery_categories)
    ]["Number of Grievances Received on NCH"]
    .sum()
)

print("========== RETURNIQ-RELEVANT COMPLAINTS ==========")

print(f"Total NCH grievances: {total_grievances:,}")

print(
    f"ReturnIQ-relevant categories: "
    f"{returniq_total:,} "
    f"({returniq_total / total_grievances * 100:.2f}%)"
)

print(
    f"Delivery/Product issue categories: "
    f"{delivery_total:,} "
    f"({delivery_total / total_grievances * 100:.2f}%)"
)

print(
    f"Refund/Replacement categories: "
    f"{refund_total:,} "
    f"({refund_total / total_grievances * 100:.2f}%)"
)

print("\n========== INCLUDED CATEGORIES ==========")

for category in returniq_categories:
    count = df_complaints_clean.loc[
        df_complaints_clean["Nature of Grievances"] == category,
        "Number of Grievances Received on NCH"
    ].sum()

    percentage = count / total_grievances * 100

    print(
        f"{category}: "
        f"{count:,} ({percentage:.2f}%)"
    )

========== RETURNIQ-RELEVANT COMPLAINTS ==========
Total NCH grievances: 397,333
ReturnIQ-relevant categories: 212,120 (53.39%)
Delivery/Product issue categories: 193,100 (48.60%)
Refund/Replacement categories: 70,017 (17.62%)

========== INCLUDED CATEGORIES ==========
Delivery of Wrong Product: 54,563 (13.73%)
Delivery of Defective / Damage Product: 53,285 (13.41%)
Non-Delivery of Product: 42,781 (10.77%)
Delay in Delivery of Product: 27,394 (6.89%)
Replacement / Refund not provided - As per policy: 19,020 (4.79%)
Product / Product Accessories Missing: 15,077 (3.79%)

### Part 4

In [20]:
# ============================================
# STEP 32.16 — RETURN & COMPLAINT ANALYSIS
# PART 4: ONLINE RETAIL II RETURN-SIGNAL ANALYSIS
# ============================================

print("========== ONLINE RETAIL II RETURN-SIGNAL ANALYSIS ==========")

# Check required columns
required_columns = [
    "Quantity",
    "Price",
    "Customer ID",
    "Country"
]

print("\nAvailable required columns:")

for col in required_columns:
    print(f"{col}: {col in df_online_retail_clean.columns}")


# ============================================
# BASIC QUANTITY ANALYSIS
# ============================================

print("\n========== QUANTITY ANALYSIS ==========")

total_records = len(df_online_retail_clean)

negative_quantity_records = (
    df_online_retail_clean["Quantity"] < 0
).sum()

positive_quantity_records = (
    df_online_retail_clean["Quantity"] > 0
).sum()

zero_quantity_records = (
    df_online_retail_clean["Quantity"] == 0
).sum()

print(f"Total transaction records: {total_records:,}")

print(
    f"Negative-quantity records: "
    f"{negative_quantity_records:,} "
    f"({negative_quantity_records / total_records * 100:.2f}%)"
)

print(
    f"Positive-quantity records: "
    f"{positive_quantity_records:,} "
    f"({positive_quantity_records / total_records * 100:.2f}%)"
)

print(
    f"Zero-quantity records: "
    f"{zero_quantity_records:,} "
    f"({zero_quantity_records / total_records * 100:.2f}%)"
)


# ============================================
# RETURN-SIGNAL QUANTITY
# ============================================

negative_quantity_total = (
    df_online_retail_clean.loc[
        df_online_retail_clean["Quantity"] < 0,
        "Quantity"
    ].sum()
)

print("\n========== NEGATIVE QUANTITY ==========")

print(
    f"Total negative quantity: "
    f"{negative_quantity_total:,}"
)


# ============================================
# RETURN-SIGNAL TRANSACTION VALUE
# ============================================

if "Price" in df_online_retail_clean.columns:

    negative_records = df_online_retail_clean[
        df_online_retail_clean["Quantity"] < 0
    ].copy()

    negative_records["Transaction_Value"] = (
        negative_records["Quantity"].abs()
        * negative_records["Price"]
    )

    print(
        f"Estimated value represented by "
        f"negative-quantity records: "
        f"{negative_records['Transaction_Value'].sum():,.2f}"
    )


# ============================================
# CUSTOMER-LEVEL RETURN SIGNAL
# ============================================

if "Customer ID" in df_online_retail_clean.columns:

    customer_return_signals = (
        df_online_retail_clean[
            df_online_retail_clean["Quantity"] < 0
        ]
        .groupby("Customer ID")
        .size()
        .sort_values(ascending=False)
    )

    print("\n========== TOP CUSTOMERS BY RETURN SIGNAL ==========")

    print(
        customer_return_signals.head(10)
    )


# ============================================
# COUNTRY-LEVEL RETURN SIGNAL
# ============================================

if "Country" in df_online_retail_clean.columns:

    country_return_signals = (
        df_online_retail_clean[
            df_online_retail_clean["Quantity"] < 0
        ]
        .groupby("Country")
        .size()
        .sort_values(ascending=False)
    )

    print("\n========== TOP COUNTRIES BY RETURN SIGNAL ==========")

    print(
        country_return_signals.head(10)
    )


print("\n========== INTERPRETATION ==========")

print(
    "Negative-quantity transactions are treated as "
    "return/cancellation signals rather than confirmed "
    "product returns."
)

========== ONLINE RETAIL II RETURN-SIGNAL ANALYSIS ==========

Available required columns:
Quantity: True
Price: True
Customer ID: True
Country: True

========== QUANTITY ANALYSIS ==========
Total transaction records: 514,912
Negative-quantity records: 10,181 (1.98%)
Positive-quantity records: 504,731 (98.02%)
Zero-quantity records: 0 (0.00%)

========== NEGATIVE QUANTITY ==========
Total negative quantity: -213,289
Estimated value represented by negative-quantity records: 629,808.65

========== TOP CUSTOMERS BY RETURN SIGNAL ==========
Customer ID
15311.0    171
14911.0    139
17511.0    110
14680.0    103
13798.0    102
14527.0     97
12471.0     89
12472.0     86
14277.0     83
13091.0     74
dtype: int64

========== TOP COUNTRIES BY RETURN SIGNAL ==========
Country
United Kingdom          8770
Germany                  468
France                   240
EIRE                     209
Channel Islands           85
Japan                     60
Spain                     43
Portugal                  40
Netherlands               39
United Arab Emirates      33
dtype: int64

========== INTERPRETATION ==========
Negative-quantity transactions are treated as return/cancellation signals rather than confirmed product returns.

### Part 5

In [21]:
# ============================================
# STEP 32.16 — RETURN & COMPLAINT ANALYSIS
# PART 5: COMBINE RETURN & COMPLAINT FINDINGS
# ============================================

print("========== RETURNIQ RETURN & COMPLAINT SUMMARY ==========")


# ============================================
# NCH COMPLAINT FINDINGS
# ============================================

print("\n========== NCH COMPLAINT FINDINGS ==========")

print(
    "The NCH dataset provides external evidence "
    "of common consumer complaint categories."
)

print(
    "These complaints are used as supporting evidence "
    "for ReturnIQ-related return and customer problems."
)


# ============================================
# ONLINE RETAIL II FINDINGS
# ============================================

print("\n========== ONLINE RETAIL II FINDINGS ==========")

total_transactions = len(df_online_retail_clean)

negative_transactions = (
    df_online_retail_clean["Quantity"] < 0
).sum()

negative_percentage = (
    negative_transactions / total_transactions * 100
)

negative_quantity = (
    df_online_retail_clean.loc[
        df_online_retail_clean["Quantity"] < 0,
        "Quantity"
    ].sum()
)

print(
    f"Total transaction records: "
    f"{total_transactions:,}"
)

print(
    f"Return/cancellation signal records: "
    f"{negative_transactions:,} "
    f"({negative_percentage:.2f}%)"
)

print(
    f"Total negative quantity: "
    f"{negative_quantity:,}"
)


# ============================================
# RETURN SIGNAL BY COUNTRY
# ============================================

print("\n========== RETURN SIGNAL BY COUNTRY ==========")

country_return_signals = (
    df_online_retail_clean[
        df_online_retail_clean["Quantity"] < 0
    ]
    .groupby("Country")
    .size()
    .sort_values(ascending=False)
)

print(
    country_return_signals.head(10)
)


# ============================================
# RETURN SIGNAL BY CUSTOMER
# ============================================

print("\n========== RETURN SIGNAL BY CUSTOMER ==========")

customer_return_signals = (
    df_online_retail_clean[
        df_online_retail_clean["Quantity"] < 0
    ]
    .groupby("Customer ID")
    .size()
    .sort_values(ascending=False)
)

print(
    customer_return_signals.head(10)
)


# ============================================
# FINAL BUSINESS FINDINGS
# ============================================

print("\n========== FINAL RETURNIQ FINDINGS ==========")

print(
    "1. Negative-quantity transactions provide "
    "a measurable return/cancellation signal."
)

print(
    "2. Return signals are concentrated among "
    "specific customers and countries."
)

print(
    "3. NCH complaint categories provide external "
    "evidence of delivery, product, refund, and "
    "replacement-related customer problems."
)

print(
    "4. These findings support the need for an "
    "AI-based return intelligence system."
)

print(
    "5. ReturnIQ can use historical transaction and "
    "customer-related features to identify patterns "
    "associated with return behavior."
)

print(
    "\nNote: Negative quantity is treated as a "
    "return/cancellation signal, not a confirmed "
    "product return."
)

========== RETURNIQ RETURN & COMPLAINT SUMMARY ==========

========== NCH COMPLAINT FINDINGS ==========
The NCH dataset provides external evidence of common consumer complaint categories.
These complaints are used as supporting evidence for ReturnIQ-related return and customer problems.

========== ONLINE RETAIL II FINDINGS ==========
Total transaction records: 514,912
Return/cancellation signal records: 10,181 (1.98%)
Total negative quantity: -213,289

========== RETURN SIGNAL BY COUNTRY ==========
Country
United Kingdom          8770
Germany                  468
France                   240
EIRE                     209
Channel Islands           85
Japan                     60
Spain                     43
Portugal                  40
Netherlands               39
United Arab Emirates      33
dtype: int64

========== RETURN SIGNAL BY CUSTOMER ==========
Customer ID
15311.0    171
14911.0    139
17511.0    110
14680.0    103
13798.0    102
14527.0     97
12471.0     89
12472.0     86
14277.0     83
13091.0     74
dtype: int64

========== FINAL RETURNIQ FINDINGS ==========
1. Negative-quantity transactions provide a measurable return/cancellation signal.
2. Return signals are concentrated among specific customers and countries.
3. NCH complaint categories provide external evidence of delivery, product, refund, and replacement-related customer problems.
4. These findings support the need for an AI-based return intelligence system.
5. ReturnIQ can use historical transaction and customer-related features to identify patterns associated with return behavior.

Note: Negative quantity is treated as a return/cancellation signal, not a confirmed product return.

## 3.17 Final EDA Feature Review

In [22]:
# ============================================
# STEP 32.17 — FINAL EDA
# PART 1: CHECK AVAILABLE FEATURES
# ============================================

print("========== AVAILABLE FEATURES ==========")

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

========== AVAILABLE FEATURES ==========
1. order_id
2. order_item_id
3. product_id
4. seller_id
5. shipping_limit_date
6. price
7. freight_value
8. product_category_name
9. product_weight_g
10. product_length_cm
11. product_height_cm
12. product_width_cm
13. seller_zip_code_prefix
14. seller_city
15. seller_state
16. customer_id
17. order_status
18. order_purchase_timestamp
19. order_approved_at
20. order_delivered_carrier_date
21. order_delivered_customer_date
22. order_estimated_delivery_date
23. customer_unique_id
24. customer_zip_code_prefix
25. customer_city
26. customer_state
27. payment_total_value
28. payment_count
29. payment_max_installments
30. payment_types
31. review_score_mean
32. review_score_min
33. review_score_count
34. review_comments
35. product_category_name_english
36. customer_latitude
37. customer_longitude
38. seller_latitude
39. seller_longitude
40. review_available
41. payment_available
42. carrier_delivery_available
43. customer_delivery_available
44. approval_available
45. customer_location_available
46. seller_location_available
47. delivery_days
48. estimated_delivery_days
49. delivery_delay_days
50. is_delayed
51. item_total_value
52. payment_difference
53. order_item_count
54. order_total_value
55. is_multi_item_order
56. purchase_year
57. purchase_month
58. purchase_day_of_week
59. purchase_hour
60. is_weekend
61. approval_days
62. shipping_preparation_days
63. transit_days
64. transit_speed
65. delivery_status
66. order_status_group
67. seller_customer_distance_km
68. distance_category
69. freight_to_price_ratio
70. high_freight_ratio
71. product_volume_cm3

## EDA Complete

The observed patterns from this notebook will be used to select appropriate features and define
the ML problem. Target selection must be based on the available labels and should not assume that
historical complaint categories are individual order-level labels.